pipeline:
  test:
    image: "node:9"
    environment:
      NODE_ENV: development
    commands:
      - ./install_phantomjs.sh
      - npm config set loglevel error
      - npm set audit false
      - npm i
      - npm run quiettest
