pipeline:
  test:
    image: "node:9"
    commands:
      - npm config set loglevel error
      - npm set audit false
      - npm i
      - npm run pagesbuild
      - npm run testquiet
      - mv coverage/ dist/sched-accounts-app/coverage/
  publish:
    image: plugins/gh-pages
    secrets: [ github_username, github_password ]
    pages_directory: dist/sched-accounts-app/
