pipeline:
  test:
    image: "node:9"
    commands:
      - npm config set loglevel error
      - npm set audit false
      - npm i
      - npm run quiettest
  publish:
    image: plugins/gh-pages
    secrets: [ github_username, github_password ]
    pages_directory: dist/sched-accounts-app/
    commands: 
      - npm i
      - npm run build